name: CI

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'chore/**'
      - 'bugfix/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  ci:
    name: CI
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: dotnet format
        run: dotnet format --verify-no-changes

      - name: dotnet build
        run: dotnet build --no-incremental -warnaserror -p:SkipTailwind=true